### ISSUE TITLE
Thermal Expansion Crafting

### ISSUE THREAD

**Issue by FoxBotGames** [Vaygrim/grimco-rd1#23]
Can't upgrade a thermal expansion energy cell from hardened to reinforced in a crafting table, either the recipe doesn't exists or when crafting for higher end hopes you have to craft the reinforced (empty) cell and go from there. This discovered on the test server.  All other recipes appear to be craftable and upgradeable.

**Comment by Vaygrim** [comment]
Not a bug. Original upgrading system was always that way in Thermal Expansion. "Hardened" was basically a dead end for Energy Cells. Will be corrected in the coming 1.0.4 update.
