### ISSUE TITLE
Overall, the modpack makes you benefit too much from mob grinders

### ISSUE THREAD

**Issue by rafradek** [Vaygrim/grimco-rd1#30]
I've been playing this modpack for a while, here are some things that I didn't like:

- Chest loot scrap has a very high chance to drop powerful items. This type of scrap should only drop from lost souls mobs.
- Any type of scrap or ability totem can drop from mob grinders.
- Very high diamond and emerald spawn rate.
- Too many cities. I would love to see at least a little space between them.
- Battle axe from tiny progressions is a joke item, why is it even enabled. It makes many mods like Tinker's construct useless.
- Wands can move and speed up monster spawners. I've managed to build a grinder that spawn 1 monster per second, and it could be improved even more. The loot is extreme.
- Everlasting upgrades are cheap and too powerful, making enchants obsolete. Resistance III is equal to a full protection 4 armor set, but it is available for only 3000 experience. The same applies to strength. Rarity doesn't count as ability totems do drop from mob grinders.

**Comment by Vaygrim** [comment]
- We feel that "Chest Loot Scrap Piles" are balanced fine the way they are in terms of drop rates and drop locations.

- Any type of scrap or ability totem **can** drop from mob grinders, yes. The pack designers are okay with this arrangement as it affords a different playstyle to those that might not want to go clearing buildings constantly.

- "Too Many Cities"? You're either using non-standard world-generation, or you've added mods to the pack that actually add their own ingredients to world-gen which have resulted in side effects the pack designers have no control over. Using the pack with the intended list of mods, in the intended "Lost Cities" world-gen results in what we feel is proper and even coverage of the world map with cities. (They ARE the entire target point of the pack by the way...)

- Battle Axes from Tiny Progressions **are** more powerful than some weapons from other mods in the, pack, this is true. It doesn't matter what effects this has on Tinker's Construct however... as that mod isn't actually in the mod pack, and the pack hasn't been balanced or tuned around it being present. Have you been adding extra mods into the pack and throwing off intended design?

- Wands CAN move and speed up monster spawners, yes. Good find.

- Everlasting Abilities has been a very popular mod in the pack so far with a large majority of our playerbase.


**All in all, your list isn't actually constructive criticism, feature suggestions, or even helpful bug reports. It's a list of personal complaints based upon powercurve and personal playstyle, all of which are entirely subjective. This pack was designed by me, for me, and gamers with a similar style to mine.**

**CASUAL.**

**Yes the powercurve might not be to your liking. The loot might be a little more prevailant then you prefer. I won't be losing any sleep over your list of suggestions, sorry. This might just not be the right pack for your personal playstyle.**
