### ISSUE TITLE
Lost Souls Configuration

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/grimco-rd1#4]
I've been playing around with version RD_03 a bit and I think that the default configuration for Lost Souls may be a bit much. The primary problem I run into is that nearly all of the enhanced mobs spawn with a good amount of either armor or regeneration. It's .. painful especially if you don't have access to enchantments by the time you get there. 

You don't know true terror till you stumble upon an 80 HP Enderman with Regen and Armor. He won't kill you, but he's tanky enough to ensure the other mobs will

On the whole I think the mod may need to be toned down a little bit, damage, hp bonuses, across the board. 

Barring that I think we should at least look at replacing some of their equipment with items from elsewhere in the pack. They currently spawn with either Diamond or Iron equipment. Thermal Foundation gives us a ton of options for both armor and weapons with a bit more granular increase in damage and protection than what you see going from Iron to Diamond

**Comment by Vaygrim** [comment]
Do we know if we can disable the Regeneration trait itself? Or do we not have control over that?

**Comment by Vaygrim** [comment]
I think we can consider this 'done'.
